---

host_usrs:
# Dev users to create or remove
################################################################################
  # - { name: 'dev.user',         comment: 'WP Dev user', uid: '3201', gid: '3001', action: 'create', sudo: 1, nopasswd: 1, noexpire: 1, key: '<users public key>' }