---
# tasks file for roles/stack

- name: update all packages
  yum:
    name: "*"
    state: "latest"
    update_cache: "true"
    lock_timeout: "500"
  when: '"yes" in initial_deploy'

- name: update all packages
  yum:
    name: "*"
    state: "latest"
    update_cache: "true"
    lock_timeout: "500"
  when: '"yes" in run_update'

- name: install azure-cli repository
  yum_repository:
    name: "azure-cli"
    description: "Azure CLI"
    baseurl: "https://packages.microsoft.com/yumrepos/azure-cli"
    enabled: "yes"
    gpgcheck: "yes"
    gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
    file: "azure-cli.repo"

- name: install packages
  yum:
    name: "{{ stack_packages }}"
    state: "present"
    update_cache: "true"
    lock_timeout: "500"

- name: put SELinux in permissive mode, logging actions that would be blocked
  selinux:
    policy: "targeted"
    state: "permissive"

# - name: add hostnames to hosts file
#   debugger: on_failed
#   template:
#     src: "hosts"
#     dest: "/etc/hosts"
#     backup: "yes"
#     owner: "root"
#     group: "root"
#     mode: "0644"
