---
# tasks file for roles/azure-nsg

- name: set the local path for the dynamic rules
  set_fact:
    local_path: "./group_vars/dynamic_rules_{{ resource_group }}.yml"

- name: find out your current public IP address using https://ipify.org/
  ipify_facts:
  register: public_ip

- name: register your public ip as a fact
  set_fact:
    your_public_ip: "{{ public_ip.ansible_facts.ipify_public_ip }}"

- name: create the dynamic network security group rules
  template:
    src: "rules.j2"
    dest: "{{ local_path }}"

- name: load dynamic security group rules
  include_vars: "{{ local_path }}"

- name: create network security group for couchbase
  azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: "{{ vmss_couchbase.name }}-nsg"
    rules: "{{ cb_nsg_rules }}"
    tags: "{{ common_tags }}"

- name: create network security group for syncgateway
  azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: "{{ vmss_syncgateway.name }}-nsg"
    rules: "{{ sg_nsg_rules }}"
    tags: "{{ common_tags }}"
