---
# tasks file for roles/azure-vmss-syncgateway

- name: create the public IP address needed for the syncgateway load balancer
  azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    allocation_method: "Static"
    name: "{{ vmss_syncgateway.name }}-pip"
    tags: "{{ common_tags }}"

- name: create a syncgateway load balancer using the public IP above
  azure_rm_loadbalancer:
    resource_group: "{{ resource_group }}"
    name: "{{ vmss_syncgateway.name }}-lb"
    frontend_ip_configurations:
      - name: "{{ vmss_syncgateway.name }}-lb-frontend-ip-config"
        public_ip_address: "{{ vmss_syncgateway.name }}-pip"
    backend_address_pools:
      - name: "{{ vmss_syncgateway.name }}-lb-backend-address-pool"
    probes:
      - name: "{{ vmss_syncgateway.name }}-lb-probe"
        port: "22"
        fail_count: "3"
        protocol: "Tcp"
    inbound_nat_pools:
      - name: "{{ vmss_syncgateway.name }}-nat-ssh"
        frontend_ip_configuration_name: "{{ vmss_syncgateway.name }}-lb-frontend-ip-config"
        protocol: "Tcp"
        frontend_port_range_start: "22000"
        frontend_port_range_end: "22009"
        backend_port: "22"
      - name: "{{ vmss_syncgateway.name }}-nat-admin-ui"
        frontend_ip_configuration_name: "{{ vmss_syncgateway.name }}-lb-frontend-ip-config"
        protocol: "Tcp"
        frontend_port_range_start: "49840"
        frontend_port_range_end: "49849"
        backend_port: "4984"
      - name: "{{ vmss_syncgateway.name }}-nat-admin-ui-ssl"
        frontend_ip_configuration_name: "{{ vmss_syncgateway.name }}-lb-frontend-ip-config"
        protocol: "Tcp"
        frontend_port_range_start: "49850"
        frontend_port_range_end: "49859"
        backend_port: "4985"
    tags: "{{ common_tags }}"

- name: check the user {{ ansible_user_id }} has a key, if not create one
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
    ssh_key_file: "~/.ssh/id_rsa"

- name: create the syncgateway VMSS
  azure_rm_virtualmachinescaleset:
    resource_group: "{{ resource_group }}"
    name: "{{ vmss_syncgateway.name }}"
    short_hostname: "{{ vmss_syncgateway.short_name }}"
    vm_size: "{{ vmss_syncgateway.size }}"
    capacity: "{{ vmss_syncgateway.capacity }}"
    overprovision: "no"
    virtual_network_name: "{{ network.name }}"
    subnet_name: "{{ vmss_syncgateway.subnet_name }}"
    load_balancer: "{{ vmss_syncgateway.name }}-lb"
    security_group: "{{ vmss_syncgateway.name }}-nsg"
    admin_username: "{{ vmss_syncgateway.admin_username }}"
    ssh_password_enabled: "{{ vmss_syncgateway.key.ssh_password_enabled }}"
    ssh_public_keys:
      - path: "{{ vmss_syncgateway.key.path }}"
        key_data: "{{ vmss_syncgateway.key.data }}"
    image:
      offer: "{{ vmss_syncgateway.image.offer }}"
      publisher: "{{ vmss_syncgateway.image.publisher }}"
      sku: "{{ vmss_syncgateway.image.sku }}"
      version: "{{ vmss_syncgateway.image.version }}"
    managed_disk_type: "{{ vmss_syncgateway.disk.managed_disk_type }}"
    upgrade_policy: "{{ vmss_syncgateway.upgrade_policy }}"
    tags: "{{ common_tags }}"

- name: install syncgateway VMSS extension
  azure_rm_virtualmachinescalesetextension:
    name: "{{ vmss_syncgateway.name }}-ext"
    resource_group: "{{ resource_group }}"
    vmss_name: "{{ vmss_syncgateway.name }}"
    publisher: "Microsoft.Azure.Extensions"
    type: "CustomScript"
    type_handler_version: "2.0"
    settings: '{ "fileUris": [ "https://{{ storeage.name }}{{ the_hash }}.blob.core.windows.net/{{ storeage.container }}/syncGateway.sh", "https://{{ storeage.name }}{{ the_hash }}.blob.core.windows.net/{{ storeage.container }}/util.sh" ], "commandToExecute": "bash syncGateway.sh {{ sync_gateway.version }}" }'
    auto_upgrade_minor_version: true
