---
# tasks file for roles/azure-vmss

- name: check the user {{ ansible_user_id }} has a key, if not create one
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
    ssh_key_file: "~/.ssh/id_rsa"
  when: '"yes" in intital_deploy'

- name: create the VMSS
  azure_rm_virtualmachinescaleset:
    resource_group: "{{ resource_group }}"
    name: "{{ vmss.name }}"
    short_hostname: "{{ vmss.short_name }}"
    vm_size: "{{ vmss.size }}"
    capacity: "{{ vmss.capacity }}"
    overprovision: "{{ vmss.overprovision }}"
    virtual_network_name: "{{ vmss.vnet.name }}"
    subnet_name: "{{ vmss.vnet.subnet_name }}"
    load_balancer: "{{ vmss.vnet.load_balancer }}"
    security_group: "{{ vmss.vnet.nsg }}"
    admin_username: "{{ vmss.admin_username }}"
    ssh_password_enabled: "{{ vmss.key.ssh_password_enabled }}"
    ssh_public_keys:
      - path: "{{ vmss.key.path }}"
        key_data: "{{ vmss.key.data }}"
    image:
      offer: "{{ vmss.image.offer }}"
      publisher: "{{ vmss.image.publisher }}"
      sku: "{{ vmss.image.sku }}"
      version: "{{ vmss.image.version }}"
    managed_disk_type: "{{ vmss.disk.managed_disk_type }}"
    data_disks: "{{ vmss.disk.data_disks }}"
    upgrade_policy: "{{ vmss.upgrade_policy }}"
    tags: "{{ common_tags }}"
  when: '"yes" in intital_deploy'

- name: install VMSS extension
  azure_rm_virtualmachinescalesetextension:
    name: "{{ vmss.name }}-ext"
    resource_group: "{{ resource_group }}"
    vmss_name: "{{ vmss.name }}"
    publisher: "Microsoft.Azure.Extensions"
    type: "CustomScript"
    type_handler_version: "2.0"
    settings: '{"commandToExecute": "hostname"}'
    auto_upgrade_minor_version: true
  when: '"yes" in intital_deploy'