---
# tasks file for roles/azure-storeage

- name: create a storeage account
  azure_rm_storageaccount:
    resource_group: "{{ resource_group }}"
    location: "{{ location }}"
    name: "{{ storeage.name }}{{ the_hash }}"
    type: "{{ storeage.type }}"
    tags: "{{ common_tags }}"

- name: prepare the files for upload
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
    remote_src: "no"
  with_items: "{{ storeage.files }}"

- name: create a container and upload the scripts
  azure_rm_storageblob:
    resource_group: "{{ resource_group }}"
    storage_account_name: "{{ storeage.name }}{{ the_hash }}"
    container: "{{ storeage.container }}"
    blob: "{{ item }}"
    src: "/tmp/{{ item }}"
    public_access: "container"
    content_type: "application/text"
  with_items: "{{ storeage.files }}"