---
# tasks file for roles/azure-vmss

- name: create the public IP address needed for the couchbase load balancer
  azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    allocation_method: "Static"
    name: "{{ vmss_couchbase.name }}-lb-pip"
    tags: "{{ common_tags }}"

- name: create a couchbase load balancer using the public IP above
  azure_rm_loadbalancer:
    resource_group: "{{ resource_group }}"
    name: "{{ vmss_couchbase.name }}-lb"
    frontend_ip_configurations:
      - name: "{{ vmss_couchbase.name }}-lb-frontend-ip-config"
        public_ip_address: "{{ vmss_couchbase.name }}-lb-pip"
    backend_address_pools:
      - name: "{{ vmss_couchbase.name }}-lb-backend-address-pool"
    probes:
      - name: "{{ vmss_couchbase.name }}-lb-probe"
        port: "22"
        fail_count: "3"
        protocol: "Tcp"
    inbound_nat_pools:
      - name: "{{ vmss_couchbase.name }}-nat-ssh"
        frontend_ip_configuration_name: "{{ vmss_couchbase.name }}-lb-frontend-ip-config"
        protocol: "Tcp"
        frontend_port_range_start: "2220"
        frontend_port_range_end: "2229"
        backend_port: "22"
      - name: "{{ vmss_couchbase.name }}-nat-admin-ui"
        frontend_ip_configuration_name: "{{ vmss_couchbase.name }}-lb-frontend-ip-config"
        protocol: "Tcp"
        frontend_port_range_start: "18000"
        frontend_port_range_end: "18009"
        backend_port: "8091"
      - name: "{{ vmss_couchbase.name }}-nat-admin-ui-ssl"
        frontend_ip_configuration_name: "{{ vmss_couchbase.name }}-lb-frontend-ip-config"
        protocol: "Tcp"
        frontend_port_range_start: "18100"
        frontend_port_range_end: "18109"
        backend_port: "18091"
    tags: "{{ common_tags }}"

- name: check the user {{ ansible_user_id }} has a key, if not create one
  user:
    name: "{{ ansible_user_id }}"
    generate_ssh_key: yes
    ssh_key_file: "~/.ssh/id_rsa"

- name: create the couchbase VMSS
  azure_rm_virtualmachinescaleset:
    resource_group: "{{ resource_group }}"
    name: "{{ vmss_couchbase.name }}-vmss"
    short_hostname: "{{ vmss_couchbase.short_name }}"
    vm_size: "{{ vmss_couchbase.size }}"
    capacity: "{{ vmss_couchbase.capacity }}"
    overprovision: "no"
    virtual_network_name: "{{ network.name }}"
    subnet_name: "{{ vmss_couchbase.subnet_name }}"
    load_balancer: "{{ vmss_couchbase.name }}-lb"
    security_group: "{{ vmss_couchbase.name }}-nsg"
    admin_username: "{{ vmss_couchbase.admin_username }}"
    ssh_password_enabled: "{{ vmss_couchbase.key.ssh_password_enabled }}"
    ssh_public_keys:
      - path: "{{ vmss_couchbase.key.path }}"
        key_data: "{{ vmss_couchbase.key.data }}"
    image:
      offer: "{{ vmss_couchbase.image.offer }}"
      publisher: "{{ vmss_couchbase.image.publisher }}"
      sku: "{{ vmss_couchbase.image.sku }}"
      version: "{{ vmss_couchbase.image.version }}"
    managed_disk_type: "{{ vmss_couchbase.disk.managed_disk_type }}"
    data_disks: "{{ vmss_couchbase.disk.data_disks }}"
    upgrade_policy: "{{ vmss_couchbase.upgrade_policy }}"
    tags: "{{ common_tags }}"

- name: install couchbase VMSS extension
  azure_rm_virtualmachinescalesetextension:
    name: "{{ vmss_couchbase.name }}-couchbase-server-vmss-ext"
    resource_group: "{{ resource_group }}"
    vmss_name: "{{ vmss_couchbase.name }}-vmss"
    publisher: "Microsoft.Azure.Extensions"
    type: "CustomScript"
    type_handler_version: "2.0"
    settings: '{ "fileUris": [ "https://{{ storage.name }}{{ the_hash }}.blob.core.windows.net/{{ storage.container }}/server.sh", "https://{{ storage.name }}{{ the_hash }}.blob.core.windows.net/{{ storage.container }}/util.sh" ], "commandToExecute": "bash server.sh {{ couchbase.version }} {{ couchbase.username }} {{ couchbase.password }} {{ couchbase.services }}" }'
    auto_upgrade_minor_version: true
