---
# tasks file for roles/azure-storage

- name: create a storage account
  azure_rm_storageaccount:
    resource_group: "{{ resource_group }}"
    location: "{{ location }}"
    name: "{{ storage.name }}{{ the_hash }}"
    type: "{{ storage.type }}"
    tags: "{{ common_tags }}"
  when: '"yes" in initial_deploy'

- name: prepare the files for upload
  template:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items: "{{ storage.files }}"
  when: '"yes" in initial_deploy'

- name: create a container and upload the scripts
  azure_rm_storageblob:
    resource_group: "{{ resource_group }}"
    storage_account_name: "{{ storage.name }}{{ the_hash }}"
    container: "{{ storage.container }}"
    blob: "{{ item }}"
    src: "/tmp/{{ item }}"
    public_access: "container"
    content_type: "application/text"
  with_items: "{{ storage.files }}"
  when: '"yes" in initial_deploy'