---
# tasks file for roles/azure-rg

- name: create a resource group
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    location: "{{ location }}"
    tags: "{{ common_tags }}"
  when: '"yes" in initial_deploy'