---
# tasks file for roles/nginx

- name: install nginx stable repository
  yum_repository:
    name: "nginx-stable"
    description: nginx stable repo
    baseurl: h"ttp://nginx.org/packages/centos/$releasever/$basearch/"
    enabled: "no"
    gpgcheck: "yes"
    gpgkey: "https://nginx.org/keys/nginx_signing.key"
    file: "nginx.repo"

- name: install nginx mainline repository
  yum_repository:
    name: "nginx-mainline"
    description: "nginx mainline repo"
    baseurl: "http://nginx.org/packages/mainline/centos/$releasever/$basearch/"
    enabled: "yes"
    gpgcheck: "yes"
    gpgkey: "https://nginx.org/keys/nginx_signing.key"
    file: "nginx.repo"

- name: install packages
  yum:
    name: "{{ nginx_packages }}"
    state: "present"
    lock_timeout: "500"

- name: create nginx ssl directory
  file:
    dest: "/etc/nginx/ssl"
    state: "directory"
    owner: "nginx"
    group: "nginx"
    mode: "0750"
  notify: "restart nginx"

- name: copy self signed certificate to instance
  copy:
    src: "{{ item }}"
    dest: "/etc/nginx/ssl/{{ item }}"
    owner: "nginx"
    group: "nginx"
    mode: "0644"
  with_items:
    - wssscert.pem
    - wssskey.pem
  notify: "restart nginx"