---
# tasks file for roles/server-sync-tests


# this should be like running curl -u public:public localhost:8092/builtAt
- name: run "builtAt" check
  uri:
    url: "http://localhost:8092/builtAt"
    user: "public"
    password: "public"
    method: "GET"
    return_content: "yes"
    status_code: "200"
    body_format: "json"
  register: builtAt_output
  ignore_errors: true

- name: print builtAt_output
  debug:
    msg: "{{ builtAt_output }}"

# this should be like running curl -u public:public localhost:8092/routedAt
- name: run "routedAt" check
  uri:
    url: "http://localhost:8092/routedAt"
    user: "public"
    password: "public"
    method: "GET"
    return_content: "yes"
    status_code: "200"
    body_format: "json"
  register: routedAt_output
  ignore_errors: true

- name: print routedAt_output
  debug:
    msg: "{{ routedAt_output }}"

# this should be like running curl -u public:public localhost:8092/notifiedAt
- name: run "notifiedAt" check
  uri:
    url: "http://localhost:8092/notifiedAt"
    user: "public"
    password: "public"
    method: "GET"
    return_content: "yes"
    status_code: "200"
    body_format: "json"
  register: notifiedAt_output
  ignore_errors: true

- name: print notifiedAt_output
  debug:
    msg: "{{ notifiedAt_output }}"

# this should be like running curl -u public:public http://localhost:9092/version 
- name: run "MiiVapi version" check
  uri:
    url: "http://localhost:9092/version"
    user: "public"
    password: "public"
    method: "GET"
    return_content: "yes"
    status_code: "200"
    body_format: "json"
  register: miivapiVersion_output
  ignore_errors: true

- name: print miivapiVersion_output
  debug:
    msg: "{{ miivapiVersion_output }}"  

# this should be like running curl -v -u public:public localhost:8092/admincorp/updateSelf -X POST -d {} 
- name: run "updateSelf" check
  uri:
    url: "http://localhost:8092/admincorp/updateSelf"
    user: "public"
    password: "public"
    method: "POST"
    return_content: "yes"
    status_code: "200"
    force_basic_auth: "yes"
    body_format: "json"
    body: "{}"
  register: updateSelf_output
  ignore_errors: true

# this should be like running curl -u public:public localhost:8092/shared/corporate
- name: run "corporate" check
  uri:
    url: "http://localhost:8092/shared/corporate"
    user: "public"
    password: "public"
    force_basic_auth: "yes"
    method: "GET"
    return_content: "yes"
    status_code: "200"
    body_format: "json"
  register: corporate_output
  ignore_errors: true

- name: print corporate_output
  debug:
    msg: "{{ corporate_output }}"
    