---
# tasks file for roles/whitespace

- name : copy container template
  copy:
    src: "sync_gateway.json"
    dest: "/home/sync_gateway/sync_gateway.json"
  notify: "restart sync_gateway"
  become_user: "{{ sync_gateway_user }}"
  become: true
  tags:
      - "application"

- name: copy azure scripts
  copy:
    src: "{{ item }}"
    dest: "/home/{{ docker_user }}/{{ item }}"
    mode: "0744"
  with_items:
    - "updateAllContainers.sh"
    - "updateReVAPI.sh"
  become_user: "{{ docker_user }}"
  become: true
  tags:
      - "application"

- name: Log into private registry and force re-authorization
  docker_login:
    registry: wsinternalcontainerregistry.azurecr.io
    username: "{{ docker_registry_user }}"
    password: "{{ docker_registry_password }}"
    reauthorize: "yes"
  become_user: "{{ docker_user }}"
  become: true
  tags:
      - "application"

- name: create docker folder
  file:
    path: "/home/{{ docker_user }}/docker"
    state: "directory"
  become_user: "{{ docker_user }}"
  become: true
  tags:
      - "application"

- name: copy docker compose file
  copy:
    src: "docker-compose.yml"
    dest: "/home/{{ docker_user }}/docker/docker-compose.yml"
  become_user: "{{ docker_user }}"
  become: true
  tags:
      - "application"