---
# defaults file for roles/docker

docker_packages:
    - "ca-certificates"
    - "yum-utils"
    - "device-mapper-persistent-data"
    - "lvm2"
    - "docker-ce"
    - "python-docker-py"
    - "python2-pip"

docker:
  user: "admin-user"
  uid: 3199
