version: '3'
services:
  revapi:
    image: wsinternalcontainerregistry.azurecr.io/revapi:latest
    ports:
      - "8092:8092"
      - "8080:8080"
    environment:
      - ENVCONFIG=apiprod
    restart: always
#    network_mode: host
    extra_hosts:
    - "localN1QL:10.0.0.4"
    - "localSG:10.0.0.7"
  pdf-fragment-service:
    image: wsinternalcontainerregistry.azurecr.io/pdf-fragment-service:latest
    ports:
      - "3000:3000"
    restart: always
  rebrowse:
    image: wsinternalcontainerregistry.azurecr.io/rebrowse:latest
    ports:
      - "9080:80"
    restart: always
  lock-monitor:
    image: wsinternalcontainerregistry.azurecr.io/lock-monitor:latest
    volumes:
      - "/home/azureuser/lock-monitor-logs:/logs"
    restart: always
    extra_hosts:
      - "localSG:10.0.0.7"    
#  tollgatepublic:
#    image: wsinternalcontainerregistry.azurecr.io/tollgate:latest
#    volumes:
#      - "/mnt/AzureFileShare/tollgatefiles:/var/tollgate"
#    ports:
#      - "8083:8083"
#    restart: always
#    environment:
#     - ENVCONFIG=public
#  tollgateadmin:
#    image: wsinternalcontainerregistry.azurecr.io/tollgate:latest
#    volumes:
#      - "/mnt/AzureFileShare/tollgatefiles:/var/tollgate"
#    ports:
#      - "18101:8085"
#    restart: always
#    environment:
#    - ENVCONFIG=admin
